apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reviews-ui-ingress
  namespace: ps-task
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "reviews-ui-ip"
    networking.gke.io/managed-certificates: "reviews-ui-cert"
spec:
  rules:
    - host: reviews.dmytrozah.dev
      http:
        paths:
          - path: /profile
            pathType: Exact
            backend:
              service:
                name: gateway
                port:
                  number: 80

          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-reviews-ui
                port:
                  number: 80