apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gateway-backendconfig
  namespace: ps-task
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    port: 1000
    requestPath: /health
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth