apiVersion: v1
kind: Secret
metadata:
  name: service-email-secret
  namespace: ps-task
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: "rabbit"
  SPRING_RABBITMQ_PASSWORD: "s@cr3t"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
