apiVersion: v1
kind: Secret
metadata:
  name: service-authors-secret
  namespace: ps-task
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "root"
  SPRING_RABBITMQ_USERNAME: "rabbit"
  SPRING_RABBITMQ_PASSWORD: "s@cr3t"
