apiVersion: v1
kind: ConfigMap
metadata:
  name: service-email-config
  namespace: ps-task
data:
  SERVER_PORT: "1001"
  SPRING_PROFILES_ACTIVE: "k8s"

  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"

  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"

  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
