apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: ps-task
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: ui
      port: 8025
      targetPort: 8025
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: ps-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          ports:
            - containerPort: 1025
            - containerPort: 8025
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: 8025
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: 8025
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"